### ISSUE TITLE
P2PDMA Host Memory Usage

### ISSUE THREAD

**Issue by nickbeckwith** [developer-onizuka/what_is_GPUDirect-Storage#1]
I really appreciate the time you've spent on this great writeup. I noticed you mentioned that host memory is not at all used during GDS. Instead GDS uses GPU BAR space to set up DMA (and NVMe submission queues?).

```
But, please note that any host memories are not at all involved with GDS operations.

I guess Controller Memory Buffer (CMB) which NVMe controller exposes could contribute performance improvement on GDS which utilizes P2P DMA. But GDS is actually using the BAR space on GPU card for P2P DMA.
```

How did you reason that NVIDIA doesn't use the CMB or host memory and uses the GPU BAR space for setting up DMA?

**Comment by developer-onizuka** [comment]
Hi Nick,

DMA is a copy between host memory and device's memory. After DMA between host and device, Device's DMA Engine interrupts to CPU so that CPU can start copying this DMAed data (it's still in kernel space) to the user space by CPU load.

But, if DMA is directly performed between PCI device's memories, it is not necessary to use and intermediate Host Memory. 

Of course, DMA works not only between host memory and device's memory but also between two devices without host memory, actually. This is a p2pdma. For example, you can use "from GPU's BAR space to NVMe's BAR space" or "from GPU's BAR space to NVMe's CMB" for writing GPU's data to NVMe. CMB aims to make the DRAM space in part of the SSD accessible directly through the PCI address space. It is a very suitable technology for GDS.
But I believe CMB was just getting started to implement at some NVMe Vendors. This might be a kind of reasons it is not used today.

Anyway, it was difficult for NVMe DMA engine to know the BAR of GPU without any Nvidia's libraries.

Best,

**Comment by nickbeckwith** [comment]
Thank you for the response and the writeup!
